name: Docker Build and Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Push the Docker image
      env:
        DOCKER_SERVER: ${{secrets.DOCKER_SERVER}} 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_KEY: ${{secrets.DOCKER_KEY}}
      run: |
        echo 'Docker login'
        docker login -u $DOCKER_USER -p $DOCKER_KEY $DOCKER_SERVER
        echo 'Building the image'
        docker build . --file BlazorPortfolioBlog/Server/Dockerfile --tag $DOCKER_SERVER/blazorportfolioblog:latest
        echo 'Pushing the image'
        docker push $DOCKER_SERVER/blazorportfolioblog:latest

